apiVersion: v1
kind: Service
metadata:
  name: {{ include "brain-researcher.fullname" . }}-neo4j
  namespace: {{ .Values.namespaces.core }}
  labels:
    {{- include "brain-researcher.labels" . | nindent 4 }}
    app.kubernetes.io/component: neo4j
spec:
  type: ClusterIP
  ports:
    - port: 7474
      targetPort: 7474
      protocol: TCP
      name: http
    - port: 7687
      targetPort: 7687
      protocol: TCP
      name: bolt
  selector:
    {{- include "brain-researcher.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: neo4j
