"""Behavioral data contracts (trials + QC report).

These lightweight Pydantic models standardize trial-level records and QC
summaries so behavior tools can pass structured data through the agent,
auditing, and workflow layers.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from brain_researcher.core.contracts.violation import Violation


class BehaviorTrial(BaseModel):
    """Canonical trial-level behavioral record (v1)."""

    schema_version: Literal["behavior-trial-v1"] = "behavior-trial-v1"

    subject_id: str | None = Field(
        default=None, description="Subject identifier if available"
    )
    session: str | None = Field(default=None, description="Session label if present")
    run: str | int | None = Field(default=None, description="Run label/index if present")

    trial_index: int = Field(
        ..., ge=0, description="Zero-based trial index in source file/order"
    )
    trial_type: str | None = Field(
        default=None, description="Condition/trial type label from the task"
    )
    condition_label: str | None = Field(
        default=None, description="Optional higher-level condition name"
    )

    onset_sec: float = Field(
        ..., description="Trial onset in seconds (relative to run start)"
    )
    duration_sec: float | None = Field(
        default=None, description="Trial duration in seconds if available"
    )
    response: str | None = Field(
        default=None, description="Recorded response/keypress/value if any"
    )
    rt_sec: float | None = Field(
        default=None, description="Reaction time in seconds (None if missing)"
    )
    correct: bool | None = Field(
        default=None, description="True/False for correctness, None if undefined"
    )

    is_excluded: bool = Field(
        default=False, description="Whether this trial should be excluded from analysis"
    )
    exclusion_reason: str | None = Field(
        default=None, description="Human-readable reason for exclusion"
    )
    exclusion_codes: list[str] = Field(
        default_factory=list, description="Machine-readable exclusion codes applied"
    )

    stimulus_id: str | None = Field(
        default=None, description="Stimulus identifier if provided by the task"
    )
    raw_source: str | None = Field(
        default=None, description="Pointer to raw source (e.g., file:line) for auditing"
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Additional task-specific fields"
    )


class BehaviorQCReport(BaseModel):
    """QC + outlier summary for a behavior table."""

    schema_version: Literal["behavior-qc-report-v1"] = "behavior-qc-report-v1"

    policy_id: str | None = Field(default=None, description="Applied QC/outlier policy ID")
    total_trials: int = Field(..., ge=0, description="Total trials ingested")
    kept_trials: int = Field(..., ge=0, description="Trials retained after exclusion")
    excluded_trials: int = Field(..., ge=0, description="Trials excluded by policy")

    exclusion_counts: dict[str, int] = Field(
        default_factory=dict, description="Counts per exclusion code"
    )

    accuracy: float | None = Field(
        default=None, description="Fraction correct across trials (0-1)"
    )
    miss_rate: float | None = Field(
        default=None, description="Fraction of trials with no response (0-1)"
    )

    rt_sec_summary: dict[str, float] | None = Field(
        default=None, description="Summary stats for RT (min/mean/median/max)"
    )

    violations: list[Violation] = Field(
        default_factory=list, description="Structured violations generated by gates"
    )
    notes: list[str] = Field(default_factory=list, description="Human-readable notes")


__all__ = [
    "BehaviorTrial",
    "BehaviorQCReport",
]
