"""Canonical runtime helpers for BR-KG Neo4j schema setup."""

from __future__ import annotations

from typing import Any


def setup_schema(db: Any) -> None:
    """Create BR-KG constraints and indexes on the provided DB handle."""

    db.create_constraint("Concept", "id", "UNIQUE")
    db.create_constraint("Task", "id", "UNIQUE")
    db.create_constraint("Publication", "pmid", "UNIQUE")
    db.create_constraint("Region", "name", "UNIQUE")
    db.create_constraint("Dataset", "id", "UNIQUE")
    db.create_constraint("Tool", "id", "UNIQUE")
    db.create_constraint("Tool", "tool_id", "UNIQUE")
    db.create_constraint("ToolFamily", "id", "UNIQUE")
    db.create_constraint("ToolVersion", "version_id", "UNIQUE")
    db.create_constraint("ToolVersion", "id", "UNIQUE")
    db.create_constraint("Operation", "id", "UNIQUE")
    db.create_constraint("ResourceType", "name", "UNIQUE")
    db.create_constraint("Modality", "name", "UNIQUE")
    db.create_constraint("Study", "id", "UNIQUE")
    db.create_constraint("DiseaseTrait", "id", "UNIQUE")
    db.create_constraint("Population", "id", "UNIQUE")
    db.create_constraint("Gene", "id", "UNIQUE")
    db.create_constraint("RiskLocus", "id", "UNIQUE")
    db.create_constraint("AgentSession", "id", "UNIQUE")
    db.create_constraint("TaskSurface", "id", "UNIQUE")
    db.create_constraint("ValidationEvidence", "id", "UNIQUE")
    db.create_constraint("OpenRisk", "id", "UNIQUE")
    db.create_constraint("Outcome", "id", "UNIQUE")
    db.create_constraint("Lesson", "id", "UNIQUE")
    db.create_constraint("NextAction", "id", "UNIQUE")

    db.create_index("Concept", "name")
    db.create_index("Task", "name")
    db.create_index("Publication", "title")
    db.create_index("Publication", "pmid")
    db.create_index("Region", "abbreviation")
    db.create_index("Dataset", "accession")
    db.create_index("Coordinate", "x")
    db.create_index("Coordinate", "y")
    db.create_index("Coordinate", "z")
    db.create_index("Tool", "name")
    db.create_index("Tool", "package")
    db.create_index("Tool", "runtime_kind")
    db.create_index("ToolFamily", "name")
    db.create_index("ToolVersion", "tool_id")
    db.create_index("Study", "name")
    db.create_index("Study", "pmid")
    db.create_index("DiseaseTrait", "name")
    db.create_index("Population", "name")
    db.create_index("Population", "ancestry_code")
    db.create_index("Gene", "symbol")
    db.create_index("RiskLocus", "name")
    db.create_index("AgentSession", "session_id")
    db.create_index("AgentSession", "source_client")
    db.create_index("AgentSession", "status")
    db.create_index("AgentSession", "last_event_at")
    db.create_index("TaskSurface", "name")
    db.create_index("ValidationEvidence", "evidence_type")
    db.create_index("OpenRisk", "label")
    db.create_index("Lesson", "issue_code")
    db.create_index("Lesson", "status")
    db.create_index("NextAction", "action_type")
