"""
Migration: Add evidence query performance indexes
Version: 004_evidence_indexes
Created: 2025-01-17
"""

from brain_researcher.services.neurokg.migrations import Migration
import logging

logger = logging.getLogger(__name__)


class Migration_004(Migration):
    """
    Add Neo4j indexes for evidence query performance.
    Targets ONVOC concept evidence queries to meet <150ms summary, <300ms evidence goals.
    """

    def __init__(self):
        super().__init__(
            version="004_evidence_indexes",
            description="Add Neo4j indexes for evidence queries"
        )

    def up(self, db):
        """
        Create Neo4j indexes for evidence endpoints.
        Supports both Neo4jGraphDB and raw neo4j.Driver instances.
        """
        # Check if db is Neo4j driver or Neo4jGraphDB wrapper
        if hasattr(db, 'execute_query'):
            # Neo4jGraphDB wrapper
            neo4j_execute = db.execute_query
        elif hasattr(db, 'session'):
            # Raw neo4j.Driver
            def neo4j_execute(cypher, params=None):
                with db.session() as session:
                    result = session.run(cypher, params or {})
                    return [record.data() for record in result]
        else:
            # Not a Neo4j database - fail fast so migration is not marked applied
            raise RuntimeError("Migration 004 requires a Neo4j database (execute_query or session missing)")

        try:
            # Composite index for ONVOC concept lookup
            logger.info("Creating index: Concept(scheme, id)")
            neo4j_execute(
                "CREATE INDEX concept_onvoc_lookup IF NOT EXISTS "
                "FOR (c:Concept) ON (c.scheme, c.id)"
            )

            # StatMap filtering indexes
            logger.info("Creating index: StatMap(space)")
            neo4j_execute(
                "CREATE INDEX statmap_space IF NOT EXISTS "
                "FOR (m:StatMap) ON (m.space)"
            )

            logger.info("Creating index: StatMap(atlas)")
            neo4j_execute(
                "CREATE INDEX statmap_atlas IF NOT EXISTS "
                "FOR (m:StatMap) ON (m.atlas)"
            )

            # Publication sorting index
            logger.info("Creating index: Publication(year)")
            neo4j_execute(
                "CREATE INDEX publication_year IF NOT EXISTS "
                "FOR (p:Publication) ON (p.year)"
            )

            # Coordinate anchor index for evidence retrieval
            logger.info("Creating index: CoordAnchor(x, y, z)")
            neo4j_execute(
                "CREATE INDEX coordanchor_xyz IF NOT EXISTS "
                "FOR (coord:CoordAnchor) ON (coord.x, coord.y, coord.z)"
            )

            # Optional: Unique constraint on Concept(scheme, id) for data integrity
            # Commented out to avoid conflicts with existing data
            # neo4j_execute(
            #     "CREATE CONSTRAINT concept_unique IF NOT EXISTS "
            #     "FOR (c:Concept) REQUIRE (c.scheme, c.id) IS UNIQUE"
            # )

            print("✓ Created evidence query indexes for Neo4j")
            logger.info("Evidence indexes created successfully")

        except Exception as exc:
            logger.error(f"Failed to create evidence indexes: {exc}")
            raise

    def down(self, db):
        """
        Drop evidence query indexes.
        """
        if hasattr(db, 'execute_query'):
            neo4j_execute = db.execute_query
        elif hasattr(db, 'session'):
            def neo4j_execute(cypher, params=None):
                with db.session() as session:
                    result = session.run(cypher, params or {})
                    return [record.data() for record in result]
        else:
            raise RuntimeError("Migration 004 requires a Neo4j database to drop indexes")

        try:
            # Drop indexes in reverse order
            logger.info("Dropping evidence indexes")

            # Note: Neo4j requires index names for DROP
            # These names are auto-generated by Neo4j with IF NOT EXISTS
            # Use SHOW INDEXES to find exact names, or use DROP INDEX name
            indexes_to_drop = [
                "coordanchor_xyz",
                "publication_year",
                "statmap_atlas",
                "statmap_space",
                "concept_onvoc_lookup",
            ]

            for index_name in indexes_to_drop:
                try:
                    neo4j_execute(f"DROP INDEX {index_name} IF EXISTS")
                except Exception as exc:
                    # Index might not exist or have different name
                    logger.warning(f"Could not drop index {index_name}: {exc}")

            print("✓ Dropped evidence query indexes")
            logger.info("Evidence indexes dropped successfully")

        except Exception as exc:
            logger.error(f"Failed to drop evidence indexes: {exc}")
            raise
