import path from 'node:path';

import { defineConfig, devices } from '@playwright/test';

const repoRoot = path.resolve(__dirname, '../..');
const playwrightArtifactsDir = path.join(repoRoot, 'artifacts', 'playwright');
const playwrightReportDir = path.join(repoRoot, 'artifacts', 'playwright-report');
const storageStatePath = path.join(playwrightArtifactsDir, '.auth', 'storageState.json');
const configuredWorkersRaw = process.env.PW_WORKERS || process.env.PLAYWRIGHT_WORKERS;
const configuredWorkers = configuredWorkersRaw ? Number(configuredWorkersRaw) : undefined;
const defaultWorkers = Number.isFinite(configuredWorkers) && configuredWorkers! > 0
  ? configuredWorkers
  : (process.env.CI ? 1 : 2);
const externalBaseUrl = process.env.E2E_BASE_URL ?? process.env.BASE_URL;
const localBaseUrl = 'http://localhost:3002';
const shouldStartWebServer = !externalBaseUrl;
const baseURL = externalBaseUrl ?? localBaseUrl;
const reuseExistingServer = process.env.PW_REUSE_SERVER === '1';

/**
 * Playwright configuration for E2E testing
 * @see https://playwright.dev/docs/test-configuration
 */
export default defineConfig({
  testDir: './tests/e2e',
  globalSetup: './tests/e2e/global-setup.ts',
  
  // Maximum time one test can run
  timeout: 60_000,
  
  // Expect timeout
  expect: {
    timeout: 10_000,
  },
  
  // Run tests in parallel.
  // Note: keep per-file execution serial to avoid overloading dev services.
  fullyParallel: false,
  
  // Fail the build on CI if you accidentally left test.only in the source code
  forbidOnly: !!process.env.CI,
  
  // Retry failed tests once
  retries: process.env.CI ? 2 : 1,
  
  // Cap workers locally to avoid flakiness with Next dev + heavy demos.
  workers: defaultWorkers,
  
  // Reporter to use
  reporter: [
    ['line'],
    ['html', { outputFolder: playwrightReportDir, open: 'never' }],
    ['json', { outputFile: path.join(playwrightArtifactsDir, 'results.json') }],
  ],
  
  // Shared settings for all projects
  use: {
    // Base URL for the application
    baseURL,
    // Auth + onboarding state (generated by globalSetup)
    storageState: storageStatePath,
    
    // Collect trace when retrying the failed test
    trace: 'on-first-retry',
    
    // Capture video on failure
    video: 'retain-on-failure',
    
    // Capture screenshot on failure
    screenshot: 'only-on-failure',
    
    // Viewport size
    viewport: { width: 1280, height: 720 },
    
    // Ignore HTTPS errors (for local development)
    ignoreHTTPSErrors: true,
    
    // Timeout for actions
    actionTimeout: 30_000,
    
    // Timeout for navigation
    navigationTimeout: 45_000,
  },
  
  // Configure projects for major browsers
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    
    // Optionally test on other browsers
    ...(process.env.TEST_ALL_BROWSERS ? [
      {
        name: 'firefox',
        use: { ...devices['Desktop Firefox'] },
      },
      {
        name: 'webkit',
        use: { ...devices['Desktop Safari'] },
      },
    ] : []),
    
    // Mobile testing (optional)
    ...(process.env.TEST_MOBILE ? [
      {
        name: 'Mobile Chrome',
        use: { ...devices['Pixel 5'] },
      },
      {
        name: 'Mobile Safari',
        use: { ...devices['iPhone 12'] },
      },
    ] : []),
  ],
  
  // Output folder for test artifacts
  outputDir: playwrightArtifactsDir,
  
  webServer: shouldStartWebServer
    ? {
        // Avoid ENOSPC when inotify watcher limits are low (common in CI/containers).
        command: 'WATCHPACK_POLLING=true npm run dev:3002',
        url: localBaseUrl,
        // Keep default stable for PRD gate runs; opt-in reuse via PW_REUSE_SERVER=1.
        reuseExistingServer,
        timeout: 120_000,
      }
    : undefined,
});
