"""
SPM12 Statistical Parametric Mapping implementation for the BR-KG LangGraph system.

Implements SPM12 for statistical analysis, DCM, VBM, and preprocessing
with focus on unique SPM capabilities not available in other tools.
"""

import json
import logging
import os
import tempfile
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

from pydantic import BaseModel, Field

from brain_researcher.services.tools.tool_base import (
    NeuroToolWrapper,
    ToolResult,
)

logger = logging.getLogger(__name__)


class DesignType(str, Enum):
    """SPM design types."""

    ONE_SAMPLE_T = "one_sample_t"
    TWO_SAMPLE_T = "two_sample_t"
    PAIRED_T = "paired_t"
    MULTIPLE_REGRESSION = "multiple_regression"
    FULL_FACTORIAL = "full_factorial"
    FLEXIBLE_FACTORIAL = "flexible_factorial"
    ANOVA = "anova"


class CorrectionType(str, Enum):
    """Multiple comparison correction methods."""

    NONE = "none"
    FWE = "FWE"  # Family-wise error
    FDR = "FDR"  # False discovery rate
    UNCORRECTED = "unc"


class NormalizationMethod(str, Enum):
    """SPM normalization methods."""

    EPI = "epi"
    UNIFIED = "unified"
    DARTEL = "dartel"
    SHOOT = "shoot"


class SegmentationMethod(str, Enum):
    """SPM segmentation methods."""

    STANDARD = "standard"
    UNIFIED = "unified"
    NEW_SEGMENT = "new_segment"


@dataclass
class SPM12Config:
    """Base configuration for SPM12 execution."""

    matlab_cmd: str = "matlab"
    spm_path: str = "/opt/spm12"
    mcr_path: Optional[str] = None  # For compiled SPM
    use_standalone: bool = False
    n_threads: int = 1

    def get_matlab_command(self) -> List[str]:
        """Get MATLAB command for running SPM."""
        if self.use_standalone and self.mcr_path:
            # Use compiled SPM with MCR
            return [os.path.join(self.spm_path, "run_spm12.sh"), self.mcr_path, "batch"]
        else:
            # Use MATLAB
            return [self.matlab_cmd, "-nodisplay", "-nosplash", "-nodesktop", "-r"]


# SPM12 Statistical Analysis Tool
class SPM12StatisticalArgs(BaseModel):
    """Arguments for SPM12 statistical analysis."""

    images: List[str] = Field(description="List of NIfTI images for analysis")
    design_type: DesignType = Field(description="Type of statistical design")
    output_dir: str = Field(description="Output directory for results")
    covariates: Optional[Dict[str, List[float]]] = Field(
        default=None, description="Covariates for the model"
    )
    contrasts: Dict[str, List[float]] = Field(
        default=None, description="Contrast definitions"
    )
    mask: Optional[str] = Field(default=None, description="Explicit mask image")
    correction: CorrectionType = Field(
        default=CorrectionType.FWE, description="Multiple comparison correction"
    )
    threshold: float = Field(default=0.05, description="Statistical threshold")
    extent_threshold: int = Field(default=0, description="Cluster extent threshold")


class SPM12StatisticalTool(NeuroToolWrapper):
    """SPM12 statistical analysis tool."""

    def __init__(self):
        """Initialize SPM12 statistical tool."""
        super().__init__()
        self.config = SPM12Config()

    def get_tool_name(self) -> str:
        return "spm12_statistical"

    def get_tool_description(self) -> str:
        return (
            "Perform statistical parametric mapping using SPM12. "
            "Supports various designs including factorial, regression, and group comparisons. "
            "Provides FWE/FDR correction and flexible contrast specification."
        )

    def get_args_schema(self):
        return SPM12StatisticalArgs

    def _generate_batch_script(
        self,
        images: List[str],
        design_type: DesignType,
        output_dir: str,
        covariates: Optional[Dict[str, List[float]]],
        contrasts: Dict[str, List[float]],
        mask: Optional[str],
        correction: CorrectionType,
        threshold: float,
    ) -> str:
        """Generate SPM batch script for statistical analysis."""

        script = f"""
% SPM12 Statistical Analysis Batch Script
% Generated by BR-KG

% Initialize SPM
spm('defaults', 'fmri');
spm_jobman('initcfg');

% Create output directory
if ~exist('{output_dir}', 'dir')
    mkdir('{output_dir}');
end

matlabbatch = {{}};

% Factorial Design Specification
matlabbatch{{1}}.spm.stats.factorial_design.dir = {{'{output_dir}'}};
"""

        # Add design-specific configuration
        if design_type == DesignType.ONE_SAMPLE_T:
            script += f"""
matlabbatch{{1}}.spm.stats.factorial_design.des.t1.scans = {{
"""
            for img in images:
                script += f"    '{img},1'\n"
            script += "};\n"

        elif design_type == DesignType.TWO_SAMPLE_T:
            # Assume first half is group 1, second half is group 2
            mid = len(images) // 2
            script += f"""
matlabbatch{{1}}.spm.stats.factorial_design.des.t2.scans1 = {{
"""
            for img in images[:mid]:
                script += f"    '{img},1'\n"
            script += "};\n"
            script += "matlabbatch{1}.spm.stats.factorial_design.des.t2.scans2 = {\n"
            for img in images[mid:]:
                script += f"    '{img},1'\n"
            script += "};\n"

        elif design_type == DesignType.FLEXIBLE_FACTORIAL:
            script += """
matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(1).name = 'Factor1';
matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(1).dept = 0;
matlabbatch{1}.spm.stats.factorial_design.des.fblock.fac(1).variance = 1;
"""

        # Add covariates if provided
        if covariates:
            script += """
% Covariates
"""
            for i, (name, values) in enumerate(covariates.items(), 1):
                script += f"""
matlabbatch{{1}}.spm.stats.factorial_design.cov({i}).c = {values};
matlabbatch{{1}}.spm.stats.factorial_design.cov({i}).cname = '{name}';
matlabbatch{{1}}.spm.stats.factorial_design.cov({i}).iCFI = 1;
matlabbatch{{1}}.spm.stats.factorial_design.cov({i}).iCC = 1;
"""

        # Add mask if provided
        if mask:
            script += f"""
matlabbatch{{1}}.spm.stats.factorial_design.masking.em = {{'{mask},1'}};
"""

        script += (
            """
% Model Estimation
matlabbatch{2}.spm.stats.fmri_est.spmmat = {fullfile('"""
            + output_dir
            + """', 'SPM.mat')};
matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;

% Contrast Manager
matlabbatch{3}.spm.stats.con.spmmat = {fullfile('"""
            + output_dir
            + """', 'SPM.mat')};
"""
        )

        # Add contrasts
        if contrasts:
            for i, (name, weights) in enumerate(contrasts.items(), 1):
                script += f"""
matlabbatch{{3}}.spm.stats.con.consess{{{i}}}.tcon.name = '{name}';
matlabbatch{{3}}.spm.stats.con.consess{{{i}}}.tcon.weights = {weights};
matlabbatch{{3}}.spm.stats.con.consess{{{i}}}.tcon.sessrep = 'none';
"""

        script += (
            """
% Run batch
spm_jobman('run', matlabbatch);

% Generate results report
spm_results_ui('Setup', fullfile('"""
            + output_dir
            + """', 'SPM.mat'));

disp('SPM12 Statistical Analysis Complete');
exit;
"""
        )

        return script

    def _run(
        self,
        images: List[str],
        design_type: DesignType,
        output_dir: str,
        covariates: Optional[Dict[str, List[float]]] = None,
        contrasts: Dict[str, List[float]] = None,
        mask: Optional[str] = None,
        correction: CorrectionType = CorrectionType.FWE,
        threshold: float = 0.05,
        extent_threshold: int = 0,
        **kwargs,
    ) -> ToolResult:
        """Execute SPM12 statistical analysis."""
        try:
            # Validate inputs
            for img in images:
                if not os.path.exists(img):
                    return ToolResult(
                        status="error", error=f"Image not found: {img}", data={}
                    )

            # Create output directory
            os.makedirs(output_dir, exist_ok=True)

            # Generate batch script
            script = self._generate_batch_script(
                images,
                design_type,
                output_dir,
                covariates,
                contrasts,
                mask,
                correction,
                threshold,
            )

            # Save script
            script_file = os.path.join(output_dir, "spm_batch.m")
            with open(script_file, "w") as f:
                f.write(script)

            # Generate command
            matlab_cmd = self.config.get_matlab_command()
            if self.config.use_standalone:
                command = " ".join(matlab_cmd + [script_file])
            else:
                command = " ".join(matlab_cmd + [f"\"run('{script_file}')\""])

            logger.info(f"Generated SPM12 command: {command}")

            # Expected outputs
            expected_outputs = {
                "spm_mat": os.path.join(output_dir, "SPM.mat"),
                "contrasts": (
                    [
                        os.path.join(output_dir, f"con_{i:04d}.nii")
                        for i in range(1, len(contrasts) + 1)
                    ]
                    if contrasts
                    else []
                ),
                "t_maps": (
                    [
                        os.path.join(output_dir, f"spmT_{i:04d}.nii")
                        for i in range(1, len(contrasts) + 1)
                    ]
                    if contrasts
                    else []
                ),
                "batch_script": script_file,
            }

            return ToolResult(
                status="success",
                data={
                    "command": command,
                    "script_file": script_file,
                    "expected_outputs": expected_outputs,
                    "design_type": design_type.value,
                    "n_images": len(images),
                    "message": "SPM12 batch script generated. Execute the command to run analysis.",
                },
            )

        except Exception as e:
            logger.error(f"SPM12 statistical analysis failed: {str(e)}")
            return ToolResult(status="error", error=str(e), data={})


# SPM12 DCM (Dynamic Causal Modeling) Tool
class DCMModelType(str, Enum):
    """DCM model types."""

    BILINEAR = "bilinear"
    NONLINEAR = "nonlinear"
    TWO_STATE = "two_state"
    STOCHASTIC = "stochastic"


class SPM12DCMArgs(BaseModel):
    """Arguments for SPM12 Dynamic Causal Modeling."""

    voi_timeseries: Dict[str, str] = Field(
        description="VOI time series files for each region"
    )
    model_type: DCMModelType = Field(
        default=DCMModelType.BILINEAR, description="Type of DCM model"
    )
    a_matrix: List[List[int]] = Field(description="Intrinsic connectivity matrix (A)")
    b_matrix: Optional[Dict[str, List[List[int]]]] = Field(
        default=None, description="Modulatory connectivity matrices (B)"
    )
    c_matrix: Optional[List[List[int]]] = Field(
        default=None, description="Driving input matrix (C)"
    )
    tr: float = Field(description="Repetition time in seconds")
    output_dir: str = Field(description="Output directory for DCM results")


class SPM12DCMTool(NeuroToolWrapper):
    """SPM12 Dynamic Causal Modeling tool."""

    def __init__(self):
        """Initialize SPM12 DCM tool."""
        super().__init__()
        self.config = SPM12Config()

    def get_tool_name(self) -> str:
        return "spm12_dcm"

    def get_tool_description(self) -> str:
        return (
            "Perform Dynamic Causal Modeling (DCM) using SPM12 for effective connectivity analysis. "
            "Model causal interactions between brain regions and estimate connection strengths."
        )

    def get_args_schema(self):
        return SPM12DCMArgs

    def _generate_dcm_script(
        self,
        voi_timeseries: Dict[str, str],
        model_type: DCMModelType,
        a_matrix: List[List[int]],
        b_matrix: Optional[Dict[str, List[List[int]]]],
        c_matrix: Optional[List[List[int]]],
        tr: float,
        output_dir: str,
    ) -> str:
        """Generate SPM batch script for DCM analysis."""

        n_regions = len(voi_timeseries)
        region_names = list(voi_timeseries.keys())

        script = f"""
% SPM12 Dynamic Causal Modeling Script
% Generated by BR-KG

% Initialize SPM
spm('defaults', 'fmri');
spm_jobman('initcfg');

% Create output directory
if ~exist('{output_dir}', 'dir')
    mkdir('{output_dir}');
end

% Load VOI time series
VOIs = {{}};
"""

        for i, (name, file) in enumerate(voi_timeseries.items(), 1):
            script += f"""
load('{file}');
VOIs{{{i}}} = xY; % Assuming standard SPM VOI structure
VOIs{{{i}}}.name = '{name}';
"""

        script += f"""
% DCM Structure Specification
DCM = {{}};
DCM.n = {n_regions}; % Number of regions
DCM.v = length(VOIs{{1}}.u); % Number of time points

% Time series
DCM.Y.dt = {tr};
DCM.Y.X0 = ones(DCM.v, 1); % Confounds
"""

        # Add time series from VOIs
        script += """
for i = 1:DCM.n
    DCM.Y.y(:,i) = VOIs{i}.u;
    DCM.Y.name{i} = VOIs{i}.name;
end
"""

        # Add connectivity matrices
        script += f"""
% Connectivity Matrices
DCM.a = {a_matrix}; % Intrinsic connections
"""

        if b_matrix:
            script += f"""
% Modulatory connections
"""
            for i, (condition, matrix) in enumerate(b_matrix.items(), 1):
                script += f"DCM.b(:,:,{i}) = {matrix}; % {condition}\n"
        else:
            script += "DCM.b = zeros(DCM.n, DCM.n, 0); % No modulatory inputs\n"

        if c_matrix:
            script += f"DCM.c = {c_matrix}; % Driving inputs\n"
        else:
            script += "DCM.c = zeros(DCM.n, 1); % No driving inputs\n"

        script += f"""
% Model options
DCM.options.nonlinear = {1 if model_type == DCMModelType.NONLINEAR else 0};
DCM.options.two_state = {1 if model_type == DCMModelType.TWO_STATE else 0};
DCM.options.stochastic = {1 if model_type == DCMModelType.STOCHASTIC else 0};
DCM.options.analysis = 'CSD'; % Cross-spectral density
DCM.options.induced = 0;

% Estimate DCM
DCM = spm_dcm_estimate(DCM);

% Save results
save(fullfile('{output_dir}', 'DCM_results.mat'), 'DCM');

% Generate report
spm_dcm_review(DCM);
saveas(gcf, fullfile('{output_dir}', 'DCM_report.png'));

% Extract parameters
A_params = DCM.Ep.A;
if ~isempty(DCM.b)
    B_params = DCM.Ep.B;
else
    B_params = [];
end

% Save parameters as JSON for easier access
params = struct('A', A_params, 'B', B_params, 'regions', {{DCM.Y.name}});
jsonStr = jsonencode(params);
fid = fopen(fullfile('{output_dir}', 'dcm_parameters.json'), 'w');
fprintf(fid, '%s', jsonStr);
fclose(fid);

disp('DCM Analysis Complete');
exit;
"""

        return script

    def _run(
        self,
        voi_timeseries: Dict[str, str],
        model_type: DCMModelType,
        a_matrix: List[List[int]],
        tr: float,
        output_dir: str,
        b_matrix: Optional[Dict[str, List[List[int]]]] = None,
        c_matrix: Optional[List[List[int]]] = None,
        **kwargs,
    ) -> ToolResult:
        """Execute SPM12 DCM analysis."""
        try:
            # Validate VOI files
            for name, file in voi_timeseries.items():
                if not os.path.exists(file):
                    return ToolResult(
                        status="error", error=f"VOI file not found: {file}", data={}
                    )

            # Create output directory
            os.makedirs(output_dir, exist_ok=True)

            # Generate DCM script
            script = self._generate_dcm_script(
                voi_timeseries, model_type, a_matrix, b_matrix, c_matrix, tr, output_dir
            )

            # Save script
            script_file = os.path.join(output_dir, "dcm_batch.m")
            with open(script_file, "w") as f:
                f.write(script)

            # Generate command
            matlab_cmd = self.config.get_matlab_command()
            if self.config.use_standalone:
                command = " ".join(matlab_cmd + [script_file])
            else:
                command = " ".join(matlab_cmd + [f"\"run('{script_file}')\""])

            logger.info(f"Generated DCM command: {command}")

            return ToolResult(
                status="success",
                data={
                    "command": command,
                    "script_file": script_file,
                    "expected_outputs": {
                        "dcm_results": os.path.join(output_dir, "DCM_results.mat"),
                        "dcm_report": os.path.join(output_dir, "DCM_report.png"),
                        "parameters": os.path.join(output_dir, "dcm_parameters.json"),
                    },
                    "model_type": model_type.value,
                    "n_regions": len(voi_timeseries),
                    "message": "DCM script generated. Execute the command to run analysis.",
                },
            )

        except Exception as e:
            logger.error(f"DCM analysis failed: {str(e)}")
            return ToolResult(status="error", error=str(e), data={})


# SPM12 VBM (Voxel-Based Morphometry) Tool
class SPM12VBMArgs(BaseModel):
    """Arguments for SPM12 Voxel-Based Morphometry."""

    structural_images: List[str] = Field(
        description="List of T1-weighted structural images"
    )
    output_dir: str = Field(description="Output directory for VBM results")
    segmentation_method: SegmentationMethod = Field(
        default=SegmentationMethod.UNIFIED, description="Segmentation method to use"
    )
    modulation: bool = Field(
        default=True, description="Apply modulation to preserve tissue volumes"
    )
    smoothing_fwhm: float = Field(
        default=8.0, description="Smoothing kernel FWHM in mm"
    )
    create_dartel: bool = Field(
        default=False, description="Create DARTEL template from subjects"
    )


class SPM12VBMTool(NeuroToolWrapper):
    """SPM12 Voxel-Based Morphometry tool."""

    def __init__(self):
        """Initialize SPM12 VBM tool."""
        super().__init__()
        self.config = SPM12Config()

    def get_tool_name(self) -> str:
        return "spm12_vbm"

    def get_tool_description(self) -> str:
        return (
            "Perform Voxel-Based Morphometry (VBM) using SPM12 for structural brain analysis. "
            "Segment tissues, create templates, and analyze gray/white matter differences."
        )

    def get_args_schema(self):
        return SPM12VBMArgs

    def _generate_vbm_script(
        self,
        structural_images: List[str],
        output_dir: str,
        segmentation_method: SegmentationMethod,
        modulation: bool,
        smoothing_fwhm: float,
        create_dartel: bool,
    ) -> str:
        """Generate SPM batch script for VBM analysis."""

        script = f"""
% SPM12 Voxel-Based Morphometry Script
% Generated by BR-KG

% Initialize SPM
spm('defaults', 'fmri');
spm_jobman('initcfg');

% Create output directory
if ~exist('{output_dir}', 'dir')
    mkdir('{output_dir}');
end

matlabbatch = {{}};

% Segmentation
"""

        if segmentation_method == SegmentationMethod.UNIFIED:
            script += """
% Unified Segmentation
matlabbatch{1}.spm.spatial.preproc.channel.vols = {
"""
            for img in structural_images:
                script += f"    '{img},1'\n"
            script += (
                """};
matlabbatch{1}.spm.spatial.preproc.channel.biasreg = 0.001;
matlabbatch{1}.spm.spatial.preproc.channel.biasfwhm = 60;
matlabbatch{1}.spm.spatial.preproc.tissue(1).tpm = {fullfile(spm('dir'), 'tpm', 'TPM.nii,1')};
matlabbatch{1}.spm.spatial.preproc.tissue(1).ngaus = 1;
matlabbatch{1}.spm.spatial.preproc.tissue(1).native = [1 """
                + ("1" if modulation else "0")
                + """];
matlabbatch{1}.spm.spatial.preproc.tissue(1).warped = [0 0];
"""
            )

        if create_dartel:
            script += """
% DARTEL Template Creation
matlabbatch{2}.spm.tools.dartel.warp.images = {
    % Gray matter images will be added here
    % White matter images will be added here
};
matlabbatch{2}.spm.tools.dartel.warp.settings.template = 'Template';
matlabbatch{2}.spm.tools.dartel.warp.settings.rform = 0;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(1).its = 3;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(1).rparam = [4 2 1e-6];
"""

        # Add smoothing
        script += f"""
% Smoothing
matlabbatch{{3}}.spm.spatial.smooth.data = {{
    % Will be populated with segmented images
}};
matlabbatch{{3}}.spm.spatial.smooth.fwhm = [{smoothing_fwhm} {smoothing_fwhm} {smoothing_fwhm}];
matlabbatch{{3}}.spm.spatial.smooth.dtype = 0;
matlabbatch{{3}}.spm.spatial.smooth.im = 0;
matlabbatch{{3}}.spm.spatial.smooth.prefix = 's';
"""

        script += f"""
% Run batch
spm_jobman('run', matlabbatch);

% Move outputs to organized folders
movefile(fullfile(pwd, 'c1*.nii'), fullfile('{output_dir}', 'gray_matter/'));
movefile(fullfile(pwd, 'c2*.nii'), fullfile('{output_dir}', 'white_matter/'));
movefile(fullfile(pwd, 'c3*.nii'), fullfile('{output_dir}', 'csf/'));

disp('VBM Analysis Complete');
exit;
"""

        return script

    def _run(
        self,
        structural_images: List[str],
        output_dir: str,
        segmentation_method: SegmentationMethod = SegmentationMethod.UNIFIED,
        modulation: bool = True,
        smoothing_fwhm: float = 8.0,
        create_dartel: bool = False,
        **kwargs,
    ) -> ToolResult:
        """Execute SPM12 VBM analysis."""
        try:
            # Validate inputs
            for img in structural_images:
                if not os.path.exists(img):
                    return ToolResult(
                        status="error",
                        error=f"Structural image not found: {img}",
                        data={},
                    )

            # Create output directories
            os.makedirs(output_dir, exist_ok=True)
            os.makedirs(os.path.join(output_dir, "gray_matter"), exist_ok=True)
            os.makedirs(os.path.join(output_dir, "white_matter"), exist_ok=True)
            os.makedirs(os.path.join(output_dir, "csf"), exist_ok=True)

            # Generate VBM script
            script = self._generate_vbm_script(
                structural_images,
                output_dir,
                segmentation_method,
                modulation,
                smoothing_fwhm,
                create_dartel,
            )

            # Save script
            script_file = os.path.join(output_dir, "vbm_batch.m")
            with open(script_file, "w") as f:
                f.write(script)

            # Generate command
            matlab_cmd = self.config.get_matlab_command()
            if self.config.use_standalone:
                command = " ".join(matlab_cmd + [script_file])
            else:
                command = " ".join(matlab_cmd + [f"\"run('{script_file}')\""])

            logger.info(f"Generated VBM command: {command}")

            return ToolResult(
                status="success",
                data={
                    "command": command,
                    "script_file": script_file,
                    "expected_outputs": {
                        "gray_matter": os.path.join(output_dir, "gray_matter"),
                        "white_matter": os.path.join(output_dir, "white_matter"),
                        "csf": os.path.join(output_dir, "csf"),
                        "dartel_template": (
                            os.path.join(output_dir, "Template_6.nii")
                            if create_dartel
                            else None
                        ),
                    },
                    "n_subjects": len(structural_images),
                    "smoothing": f"{smoothing_fwhm}mm",
                    "message": "VBM script generated. Execute the command to run analysis.",
                },
            )

        except Exception as e:
            logger.error(f"VBM analysis failed: {str(e)}")
            return ToolResult(status="error", error=str(e), data={})


# Tool collection for registration
class SPM12Tools:
    """Collection of SPM12 tools."""

    @staticmethod
    def get_all_tools() -> List[NeuroToolWrapper]:
        """Get all SPM12 tools."""
        return [SPM12StatisticalTool(), SPM12DCMTool(), SPM12VBMTool()]
