#!/usr/bin/env python3
"""Grid-calibrate ONVOC mapping thresholds from mapping_rows artifacts.

This utility replays acceptance decisions over `mapping_rows.jsonl` generated by
`br gabriel map-onvoc` and reports how many rows would auto-accept under
alternative `min_score` / `margin_min` settings.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class ThresholdConfig:
    min_score: float
    margin_min: float


@dataclass(frozen=True)
class RowSignal:
    status: str
    reason: str
    has_candidate: bool
    score: float | None
    top1_score: float | None
    top2_score: float | None


def _as_float(value: Any) -> float | None:
    try:
        if value is None:
            return None
        return float(value)
    except (TypeError, ValueError):
        return None


def _iter_jsonl(path: Path):
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            raw = line.strip()
            if not raw:
                continue
            yield raw


def _parse_row(row: dict[str, Any]) -> RowSignal:
    status = str(row.get("status") or "").strip()
    reason = str(row.get("reason") or "").strip()
    has_candidate = bool(str(row.get("onvoc_id") or "").strip())
    score = _as_float(row.get("score"))
    top1_score = _as_float(row.get("top1_score"))
    top2_score = _as_float(row.get("top2_score"))
    return RowSignal(
        status=status,
        reason=reason,
        has_candidate=has_candidate,
        score=score,
        top1_score=top1_score,
        top2_score=top2_score,
    )


def load_mapping_rows(path: Path) -> list[RowSignal]:
    rows: list[RowSignal] = []
    for raw in _iter_jsonl(path):
        payload = json.loads(raw)
        if isinstance(payload, dict):
            rows.append(_parse_row(payload))
    return rows


def evaluate_thresholds(
    rows: list[RowSignal],
    *,
    min_score: float,
    margin_min: float,
) -> dict[str, Any]:
    parsed = len(rows)
    candidate_rows = 0
    accepted = 0
    rejected = 0
    rejected_no_candidate = 0
    rejected_below_score = 0
    rejected_margin = 0

    for row in rows:
        if not row.has_candidate or row.score is None:
            rejected += 1
            rejected_no_candidate += 1
            continue
        candidate_rows += 1

        top1 = row.top1_score if row.top1_score is not None else row.score
        top2 = row.top2_score
        margin_ok = True
        if top2 is not None:
            margin_ok = (top1 - top2) >= margin_min

        score_ok = row.score >= min_score
        if score_ok and margin_ok:
            accepted += 1
            continue

        rejected += 1
        if not score_ok:
            rejected_below_score += 1
        if not margin_ok:
            rejected_margin += 1

    acceptance_rate = accepted / parsed if parsed else 0.0
    candidate_acceptance_rate = accepted / candidate_rows if candidate_rows else 0.0

    return {
        "parsed": parsed,
        "candidate_rows": candidate_rows,
        "accepted": accepted,
        "rejected": rejected,
        "acceptance_rate": acceptance_rate,
        "candidate_acceptance_rate": candidate_acceptance_rate,
        "rejected_no_candidate": rejected_no_candidate,
        "rejected_below_score": rejected_below_score,
        "rejected_margin": rejected_margin,
        "config": {
            "min_score": min_score,
            "margin_min": margin_min,
        },
    }


def run_grid(
    rows: list[RowSignal],
    *,
    min_scores: list[float],
    margins: list[float],
    top_n: int,
) -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = []
    for min_score in sorted(set(min_scores)):
        for margin in sorted(set(margins)):
            results.append(
                evaluate_thresholds(
                    rows,
                    min_score=float(min_score),
                    margin_min=float(margin),
                )
            )
    results.sort(
        key=lambda item: (
            -int(item["accepted"]),
            -float(item["candidate_acceptance_rate"]),
            -float(item["config"]["min_score"]),
            float(item["config"]["margin_min"]),
        )
    )
    return results[: max(1, int(top_n))]


def _parse_grid_values(raw: str, *, default: list[float]) -> list[float]:
    text = str(raw or "").strip()
    if not text:
        return list(default)
    values: list[float] = []
    for part in text.split(","):
        chunk = part.strip()
        if not chunk:
            continue
        values.append(float(chunk))
    return values or list(default)


def calibrate(
    *,
    mapping_rows_path: Path,
    output_path: Path,
    min_scores: list[float],
    margins: list[float],
    top_n: int,
) -> dict[str, Any]:
    rows = load_mapping_rows(mapping_rows_path)
    baseline = evaluate_thresholds(rows, min_score=0.82, margin_min=0.04)
    top = run_grid(rows, min_scores=min_scores, margins=margins, top_n=top_n)
    best = top[0] if top else baseline

    payload = {
        "mapping_rows_path": str(mapping_rows_path),
        "rows": {
            "parsed": len(rows),
        },
        "baseline": baseline,
        "best": best,
        "top_configs": top,
        "delta_vs_baseline": {
            "accepted_delta": int(best["accepted"]) - int(baseline["accepted"]),
            "acceptance_rate_delta": float(best["acceptance_rate"]) - float(baseline["acceptance_rate"]),
        },
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, ensure_ascii=True, indent=2), encoding="utf-8")
    return payload


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Grid-calibrate ONVOC min_score/margin_min from mapping_rows.jsonl",
    )
    parser.add_argument(
        "--mapping-rows",
        type=Path,
        required=True,
        help="Path to mapping_rows.jsonl emitted by `br gabriel map-onvoc`.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output JSON path (default: <mapping_rows_dir>/onvoc_threshold_grid_summary.json).",
    )
    parser.add_argument(
        "--min-scores",
        type=str,
        default="0.72,0.74,0.76,0.78,0.80,0.82,0.84,0.86",
        help="Comma-separated min_score grid.",
    )
    parser.add_argument(
        "--margins",
        type=str,
        default="0.00,0.01,0.02,0.03,0.04",
        help="Comma-separated margin_min grid.",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=20,
        help="Number of top configs to keep.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print full JSON payload.",
    )
    args = parser.parse_args()

    mapping_rows = args.mapping_rows.expanduser().resolve()
    if not mapping_rows.exists():
        raise FileNotFoundError(f"mapping_rows not found: {mapping_rows}")

    output_path = args.output
    if output_path is None:
        output_path = mapping_rows.parent / "onvoc_threshold_grid_summary.json"
    output_path = output_path.expanduser().resolve()

    min_scores = _parse_grid_values(
        args.min_scores,
        default=[0.72, 0.74, 0.76, 0.78, 0.80, 0.82, 0.84, 0.86],
    )
    margins = _parse_grid_values(
        args.margins,
        default=[0.00, 0.01, 0.02, 0.03, 0.04],
    )

    payload = calibrate(
        mapping_rows_path=mapping_rows,
        output_path=output_path,
        min_scores=min_scores,
        margins=margins,
        top_n=max(1, int(args.top_n)),
    )

    if args.json:
        print(json.dumps(payload, ensure_ascii=True, indent=2))
    else:
        baseline = payload["baseline"]
        best = payload["best"]
        delta = payload["delta_vs_baseline"]
        print("ONVOC threshold calibration complete")
        print(f"Baseline accepted: {baseline['accepted']} @ min_score=0.82 margin=0.04")
        print(
            "Best accepted: "
            f"{best['accepted']} @ min_score={best['config']['min_score']:.2f} "
            f"margin={best['config']['margin_min']:.2f}"
        )
        print(
            "Delta vs baseline: "
            f"accepted {delta['accepted_delta']:+d}, "
            f"acceptance_rate {delta['acceptance_rate_delta']:+.4f}"
        )
        print(f"Summary: {output_path}")


if __name__ == "__main__":
    main()
