"""
Lazy exports for agent tool modules.

This keeps import time low while preserving compatibility with
``from brain_researcher.services.tools import some_module``.
"""

from __future__ import annotations

import importlib
import sys
from types import ModuleType

_MODULE_PATHS: dict[str, str] = {
    "advanced_deep_learning": "brain_researcher.services.tools.advanced_deep_learning",
    "advanced_visualization_tool": "brain_researcher.services.tools.advanced_visualization_tool",
    "afni_clustsim_tool": "brain_researcher.services.tools.afni_clustsim_tool",
    "ants_tool": "brain_researcher.services.tools.ants_tool",
    "archive_tools": "brain_researcher.services.tools.archive_tools",
    "arg_adapter": "brain_researcher.services.tools.arg_adapter",
    "args_resolver": "brain_researcher.services.tools.args_resolver",
    "asl_perfusion_tool": "brain_researcher.services.tools.asl_perfusion_tool",
    "base": "brain_researcher.services.tools.tool_base",
    "bids_tools": "brain_researcher.services.tools.bids_tools",
    "brain_simulation_tool": "brain_researcher.services.tools.brain_simulation_tool",
    "causality_analysis": "brain_researcher.services.tools.causality_analysis",
    "clinical_decision_support": "brain_researcher.services.tools.clinical_decision_support",
    "cloud_native_processing": "brain_researcher.services.tools.cloud_native_processing",
    "conn_tool": "brain_researcher.services.tools.conn_tool",
    "connectivity_measures_tool": "brain_researcher.services.tools.connectivity_measures_tool",
    "coreg_apply_xfm_tool": "brain_researcher.services.tools.coreg_apply_xfm_tool",
    "coreg_register_tool": "brain_researcher.services.tools.coreg_register_tool",
    "cpac_tool": "brain_researcher.services.tools.cpac_tool",
    "cross_validation_tool": "brain_researcher.services.tools.cross_validation_tool",
    "diffusion_tractography_tool": "brain_researcher.services.tools.diffusion_tractography_tool",
    "dl_pytorch_tool": "brain_researcher.services.tools.dl_pytorch_tool",
    "dynamic_connectivity_tool": "brain_researcher.services.tools.dynamic_connectivity_tool",
    "eeg_preprocess_tool": "brain_researcher.services.tools.eeg_preprocess_tool",
    "dmri_fit_model_tool": "brain_researcher.services.tools.dmri_fit_model_tool",
    "dmri_parcellate_connectome_tool": "brain_researcher.services.tools.dmri_parcellate_connectome_tool",
    "dmri_resolve_dwi_triplet_tool": "brain_researcher.services.tools.dmri_resolve_dwi_triplet_tool",
    "epoch_events_tool": "brain_researcher.services.tools.epoch_events_tool",
    "encoding_models_tool": "brain_researcher.services.tools.encoding_models_tool",
    "enhanced_meta_analysis": "brain_researcher.services.tools.enhanced_meta_analysis",
    "enhanced_registry": "brain_researcher.services.tools.enhanced_registry",
    "env_desc": "brain_researcher.services.tools.env_desc",
    "dependency_inspector": "brain_researcher.services.tools.dependency_inspector",
    "feature_selection_tool": "brain_researcher.services.tools.feature_selection_tool",
    "fitlins_tool": "brain_researcher.services.tools.fitlins_tool",
    "fmri_tools": "brain_researcher.services.tools.fmri_tools",
    "fmriprep_tool": "brain_researcher.services.tools.fmriprep_tool",
    "freesurfer_tool": "brain_researcher.services.tools.freesurfer_tool",
    "fsl_bedpostx_tool": "brain_researcher.services.tools.fsl_bedpostx_tool",
    "fsl_bet_tool": "brain_researcher.services.tools.fsl_bet_tool",
    "fsl_feat_tool": "brain_researcher.services.tools.fsl_feat_tool",
    "fsl_fix_tool": "brain_researcher.services.tools.fsl_fix_tool",
    "fsl_flirt_tool": "brain_researcher.services.tools.fsl_flirt_tool",
    "fsl_fnirt_tool": "brain_researcher.services.tools.fsl_fnirt_tool",
    "fsl_melodic_tool": "brain_researcher.services.tools.fsl_melodic_tool",
    "fsl_palm_tool": "brain_researcher.services.tools.fsl_palm_tool",
    "genetics_genomics_tools": "brain_researcher.services.tools.genetics_genomics_tools",
    "gnn_connectivity_tool": "brain_researcher.services.tools.gnn_connectivity_tool",
    "graph_theory_tool": "brain_researcher.services.tools.graph_theory_tool",
    "hcp_workbench_tool": "brain_researcher.services.tools.hcp_workbench_tool",
    "hrf_estimate_and_refit_tool": "brain_researcher.services.tools.hrf_estimate_and_refit_tool",
    "hyperalignment_tool": "brain_researcher.services.tools.hyperalignment_tool",
    "interactive_visualization_tools": "brain_researcher.services.tools.interactive_visualization_tools",
    "kg_evidence_bundle_tool": "brain_researcher.services.tools.kg_evidence_bundle_tool",
    "kg_ingest_tool": "brain_researcher.services.tools.kg_ingest_tool",
    "kg_novelty_tools": "brain_researcher.services.tools.kg_novelty_tools",
    "kg_multihop_qa_tool": "brain_researcher.services.tools.kg_multihop_qa_tool",
    "kg_shacl_validate_tool": "brain_researcher.services.tools.kg_shacl_validate_tool",
    "label_transfer_tool": "brain_researcher.services.tools.label_transfer_tool",
    "list_dataset_assets_tool": "brain_researcher.services.tools.list_dataset_assets_tool",
    "list_neuroimage_assets_tool": "brain_researcher.services.tools.list_neuroimage_assets_tool",
    "lesion_detection_tool": "brain_researcher.services.tools.lesion_detection_tool",
    "ieeg_connectivity_tool": "brain_researcher.services.tools.ieeg_connectivity_tool",
    "ieeg_electrode_localize_tool": "brain_researcher.services.tools.ieeg_electrode_localize_tool",
    "ieeg_epoch_features_tool": "brain_researcher.services.tools.ieeg_epoch_features_tool",
    "ieeg_preprocess_tool": "brain_researcher.services.tools.ieeg_preprocess_tool",
    "meta_align_tool": "brain_researcher.services.tools.meta_align_tool",
    "meta_analysis_tool": "brain_researcher.services.tools.meta_analysis_tool",
    "meta_brainmap_tool": "brain_researcher.services.tools.meta_brainmap_tool",
    "meta_combine_tool": "brain_researcher.services.tools.meta_combine_tool",
    "mixed_effects_tool": "brain_researcher.services.tools.mixed_effects_tool",
    "mne_autoreject_tool": "brain_researcher.services.tools.mne_autoreject_tool",
    "mne_connectivity_tool": "brain_researcher.services.tools.mne_connectivity_tool",
    "mne_fooof_tool": "brain_researcher.services.tools.mne_fooof_tool",
    "mne_ica_tool": "brain_researcher.services.tools.mne_ica_tool",
    "mne_preprocessing_tool": "brain_researcher.services.tools.mne_preprocessing_tool",
    "mne_source_tool": "brain_researcher.services.tools.mne_source_tool",
    "mne_timefreq_tool": "brain_researcher.services.tools.mne_timefreq_tool",
    "monai_tool": "brain_researcher.services.tools.monai_tool",
    "mrs_tool": "brain_researcher.services.tools.mrs_tool",
    "multimodal_fusion": "brain_researcher.services.tools.multimodal_fusion",
    "multimodal_integration_tool": "brain_researcher.services.tools.multimodal_integration_tool",
    "multiple_comparison_tool": "brain_researcher.services.tools.multiple_comparison_tool",
    "mvpa_tool": "brain_researcher.services.tools.mvpa_tool",
    "neurodesk_tools": "brain_researcher.services.tools.neurodesk_tools",
    "neurokg_bridge": "brain_researcher.services.tools.neurokg_bridge",
    "neurokg_tools": "brain_researcher.services.tools.neurokg_tools",
    "neurosynth_tools": "brain_researcher.services.tools.neurosynth_tools",
    "nilearn_connectivity": "brain_researcher.services.tools.nilearn_connectivity",
    "nilearn_glm": "brain_researcher.services.tools.nilearn_glm",
    "nilearn_mvpa": "brain_researcher.services.tools.nilearn_mvpa",
    "nilearn_preprocessing": "brain_researcher.services.tools.nilearn_preprocessing",
    "nilearn_viz": "brain_researcher.services.tools.nilearn_viz",
    "nipype_tool": "brain_researcher.services.tools.nipype_tool",
    "nwb_tools": "brain_researcher.services.tools.nwb_tools",
    "optical_imaging_tools": "brain_researcher.services.tools.optical_imaging_tools",
    "realtime_twophoton_tool": "brain_researcher.services.tools.realtime_twophoton_tool",
    "parcellation_fetch_tool": "brain_researcher.services.tools.parcellation_fetch_tool",
    "permutation_testing_tool": "brain_researcher.services.tools.permutation_testing_tool",
    "pet_coreg_tool": "brain_researcher.services.tools.pet_coreg_tool",
    "pet_imaging_tools": "brain_researcher.services.tools.pet_imaging_tools",
    "pet_parcellate_tool": "brain_researcher.services.tools.pet_parcellate_tool",
    "pet_suvr_tool": "brain_researcher.services.tools.pet_suvr_tool",
    "physio_noise_regressors_tool": "brain_researcher.services.tools.physio_noise_regressors_tool",
    "pnm_evs_regressors_tool": "brain_researcher.services.tools.pnm_evs_regressors_tool",
    "cvr_breath_hold_tool": "brain_researcher.services.tools.cvr_breath_hold_tool",
    "qbold_fabber_tool": "brain_researcher.services.tools.qbold_fabber_tool",
    "calibrated_perfusion_surrogate_tool": "brain_researcher.services.tools.calibrated_perfusion_surrogate_tool",
    "fixed_hrf_literature_scoping_tool": "brain_researcher.services.tools.fixed_hrf_literature_scoping_tool",
    "pupillometry_preprocess_tool": "brain_researcher.services.tools.pupillometry_preprocess_tool",
    "reproducibility_bundle_tool": "brain_researcher.services.tools.reproducibility_bundle_tool",
    "phase2_batch_tools": "brain_researcher.services.tools.phase2_batch_tools",
    "pipeline_tools": "brain_researcher.services.tools.pipeline_tools",
    "qc_tools": "brain_researcher.services.tools.qc_tools",
    "qsiprep_tool": "brain_researcher.services.tools.qsiprep_tool",
    "qsm_tool": "brain_researcher.services.tools.qsm_tool",
    "rag_tools": "brain_researcher.services.tools.rag_tools",
    "realtime_fmri_tool": "brain_researcher.services.tools.realtime_fmri_tool",
    "registration_tool": "brain_researcher.services.tools.registration_tool",
    "resolve_bids_tool": "brain_researcher.services.tools.resolve_bids_tool",
    "resolve_dataset_asset_tool": "brain_researcher.services.tools.resolve_dataset_asset_tool",
    "resolve_neuroimage_asset_tool": "brain_researcher.services.tools.resolve_neuroimage_asset_tool",
    "resolve_reference_map_tool": "brain_researcher.services.tools.resolve_reference_map_tool",
    "resolve_montage_tool": "brain_researcher.services.tools.resolve_montage_tool",
    "resolve_space_tool": "brain_researcher.services.tools.resolve_space_tool",
    "resolve_transform_tool": "brain_researcher.services.tools.resolve_transform_tool",
    "registry": "brain_researcher.services.tools.tool_registry",
    "rsa_toolbox_tool": "brain_researcher.services.tools.rsa_toolbox_tool",
    "searchlight_tool": "brain_researcher.services.tools.searchlight_tool",
    "segmentation_tool": "brain_researcher.services.tools.segmentation_tool",
    "smri_parcellation_stats_tool": "brain_researcher.services.tools.smri_parcellation_stats_tool",
    "smri_recon_tool": "brain_researcher.services.tools.smri_recon_tool",
    "smri_surface_export_tool": "brain_researcher.services.tools.smri_surface_export_tool",
    "spec": "brain_researcher.services.tools.spec",
    "spm12_tool": "brain_researcher.services.tools.spm12_tool",
    "statistical_inference_tool": "brain_researcher.services.tools.statistical_inference_tool",
    "statistical_tools": "brain_researcher.services.tools.statistical_tools",
    "statsmodels_glm_tool": "brain_researcher.services.tools.statsmodels_glm_tool",
    "temporal_decoding_tool": "brain_researcher.services.tools.temporal_decoding_tool",
    "timefreq_tfr_tool": "brain_researcher.services.tools.timefreq_tfr_tool",
    "tribe_tool": "brain_researcher.services.tools.tribe_tool",
    "tool_executor": "brain_researcher.services.tools.tool_executor",
    "utils": "brain_researcher.services.tools.utils",
    "xcpd_tool": "brain_researcher.services.tools.xcpd_tool",
}

__all__ = sorted(_MODULE_PATHS.keys())


def _load_module(name: str) -> ModuleType:
    """Import and cache a module by its short name."""
    module = importlib.import_module(_MODULE_PATHS[name])
    setattr(sys.modules[__name__], name, module)
    return module


def __getattr__(name: str) -> ModuleType:
    if name in _MODULE_PATHS:
        return _load_module(name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(list(globals().keys()) + __all__)
